#!/bin/zsh

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "Installing Xcode Command Line Tools..."
xcode-select --install

if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update > /dev/null
brew upgrade > /dev/null
brew install newt > /dev/null

echo "Installing Apps..."
echo "Installing python..." && brew install python > /dev/null
echo "Installing git..." && brew install git > /dev/null
echo "Installing Docker..." && brew install --casks docker > /dev/null
echo "Installing The Unarchiver..." && brew brew install --casks the-unarchiver > /dev/null
echo "Installing Visual Studio Code..." && brew brew install --casks visual-studio-code > /dev/null
echo "Installing VLC..." && brew brew install --casks vlc > /dev/null

brew cleanup
cp ./resources/.zshrc ~/.zshrc

source ~/.zshrc

echo "Installation finished"